/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { JSX } from "react";
import TableBookShelfUrl from "./TableBookShelf.glb";

type GLTFResult = GLTF & {
  nodes: {
    Table: THREE.Mesh;
    Shelf: THREE.Mesh;
    Mat: THREE.Mesh;
    CoffeeMug: THREE.Mesh;
    Circle: THREE.Mesh;
    Book: THREE.Mesh;
    BookHalf: THREE.Mesh;
    Paper: THREE.Mesh;
    Paper001: THREE.Mesh;
    RedBigBook: THREE.Mesh;
    BookHalf001: THREE.Mesh;
    Paper002: THREE.Mesh;
    Paper003: THREE.Mesh;
    BlueLittleBook: THREE.Mesh;
    BookHalf002: THREE.Mesh;
    Paper004: THREE.Mesh;
    Paper005: THREE.Mesh;
    RedBigBook001: THREE.Mesh;
    BookHalf003: THREE.Mesh;
    Paper007: THREE.Mesh;
    Paper008: THREE.Mesh;
    RedBigBook002: THREE.Mesh;
    BookHalf004: THREE.Mesh;
    Paper009: THREE.Mesh;
    Paper010: THREE.Mesh;
    RedBigBook003: THREE.Mesh;
    BookHalf005: THREE.Mesh;
    Paper011: THREE.Mesh;
    Paper012: THREE.Mesh;
  };
  materials: {
    WoodTable: THREE.MeshStandardMaterial;
    BookshelfWood: THREE.MeshStandardMaterial;
    Mat: THREE.MeshStandardMaterial;
    Cup: THREE.MeshStandardMaterial;
    Coffee: THREE.MeshStandardMaterial;
    RedBookCover: THREE.MeshStandardMaterial;
    Paper: THREE.MeshStandardMaterial;
    BlueBookCover: THREE.MeshStandardMaterial;
  };
};

export function TableBookShelf(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(TableBookShelfUrl) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="DeskScene">
        <mesh
          name="Table"
          castShadow
          receiveShadow
          geometry={nodes.Table.geometry}
          material={materials.WoodTable}
          position={[0, 0, -0.075]}
          userData={{ name: "Table" }}
        >
          <meshStandardMaterial color={"#63462D"} roughness={1} metalness={0} />
        </mesh>
        <mesh
          name="Shelf"
          castShadow
          receiveShadow
          geometry={nodes.Shelf.geometry}
          material={materials.BookshelfWood}
          position={[0, 0, -0.075]}
          scale={0.862}
          userData={{ name: "Shelf" }}
        >
          <meshStandardMaterial color={"#63462D"} roughness={1} metalness={0} />
        </mesh>
        <mesh
          name="Mat"
          castShadow
          receiveShadow
          geometry={nodes.Mat.geometry}
          material={materials.Mat}
          position={[0, 0, -0.075]}
          userData={{ name: "Mat" }}
        />
        <group>
          <mesh
            name="CoffeeMug"
            castShadow
            receiveShadow
            geometry={nodes.CoffeeMug.geometry}
            material={materials.Cup}
            position={[-0.471, 1.002, 0.265]}
            scale={[1.5, 1.5, 1.5]}
            userData={{ name: "CoffeeMug" }}
          >
            <mesh
              name="Circle"
              castShadow
              receiveShadow
              geometry={nodes.Circle.geometry}
              material={materials.Coffee}
              userData={{ name: "Circle" }}
              scale={[1, 1.2, 1]}
            />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(TableBookShelfUrl);
